{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "cd67a443",
   "metadata": {},
   "source": [
    "Esto me respondio ChatGPT:\n",
    "\n",
    "from dtaidistance import dtw\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from joblib import Parallel, delayed\n",
    "\n",
    "# Simulamos 500k series cortas (ej: 30 valores cada una)\n",
    "# En producción esto vendría de tu DataFrame\n",
    "n_series = 500_000\n",
    "series_length = 30\n",
    "series = [np.random.rand(series_length) for _ in range(n_series)]\n",
    "\n",
    "# Supongamos que querés comparar las primeras 100 contra las siguientes 1000\n",
    "query_series = series[:100]\n",
    "base_series = series[100:1100]\n",
    "\n",
    "# Calculamos DTW usando paralelización con joblib\n",
    "def compute_dtw_for_query(q_idx, q):\n",
    "    distances = [dtw.distance_fast(q, b) for b in base_series]\n",
    "    return q_idx, distances\n",
    "\n",
    "results = Parallel(n_jobs=-1)(delayed(compute_dtw_for_query)(i, q) for i, q in enumerate(query_series))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "b15ae11c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import gc\n",
    "from dtaidistance import dtw\n",
    "import hdbscan\n",
    "from sklearn.manifold import MDS\n",
    "from fastdtw import fastdtw\n",
    "from sklearn.cluster import MiniBatchKMeans\n",
    "from sklearn.metrics import pairwise_distances\n",
    "from tqdm import tqdm\n",
    "import functools\n",
    "from multiprocessing import Pool, shared_memory, cpu_count\n",
    "import pickle\n",
    "import cloudpickle\n",
    "from tqdm import tqdm"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "02647baa",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "gc.collect()\n",
    "df_full = pd.read_parquet('./data/l_vm_completa_train.parquet', engine='fastparquet')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "02e4e517",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Dejar solo las columnas CUSTOMER_ID, PRODUCT_ID, y ORDINAL, CLASE_DELTA donde PERIODO <= 201910\n",
    "df_full = df_full.loc[df_full['PERIODO'] <= 201910, ['CUSTOMER_ID', 'PRODUCT_ID', 'ORDINAL', 'CLASE_DELTA']]\n",
    "df_full = df_full.sort_values(by=['CUSTOMER_ID', 'PRODUCT_ID', 'ORDINAL'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "0610b53b",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Agrupamos por combinación de cliente y producto\n",
    "grouped = df_full.groupby(['CUSTOMER_ID', 'PRODUCT_ID'])['CLASE_DELTA'].apply(list)\n",
    "# Convertimos a DataFrame\n",
    "series_df = grouped.reset_index(name='serie_clase')\n",
    "# Extraer series como listas\n",
    "series_list = series_df['serie_clase'].tolist()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a18bc81f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Series válidas: 508660 / 690181\n",
      "Calculando matriz de distancias FastDTW...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 1000/1000 [03:17<00:00,  5.05it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Reduciendo dimensión con MDS...\n",
      "Clusters detectados: 7\n",
      "Asignando clusters usando memoria compartida y 28 procesos...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.\n",
      "  warnings.warn(\n",
      "/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.\n",
      "  warnings.warn(\n",
      "Exception ignored in: <function SharedMemory.__del__ at 0x757225135b80>Exception ignored in: \n",
      "Traceback (most recent call last):\n",
      "Exception ignored in: <function SharedMemory.__del__ at 0x757225135b80>  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 184, in __del__\n",
      "<function SharedMemory.__del__ at 0x757225135b80>    \n",
      "\n",
      "self.close()Traceback (most recent call last):\n",
      "Exception ignored in: Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 184, in __del__\n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 184, in __del__\n",
      "<function SharedMemory.__del__ at 0x757225135b80>  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 227, in close\n",
      "        \n",
      "    self.close()self.close()Exception ignored in: Traceback (most recent call last):\n",
      "\n",
      "self._mmap.close()\n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 184, in __del__\n",
      "\n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 227, in close\n",
      "<function SharedMemory.__del__ at 0x757225135b80>      File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 227, in close\n",
      "self.close()    BufferError\n",
      "Exception ignored in:     self._mmap.close(): self._mmap.close()\n",
      "Traceback (most recent call last):\n",
      "<function SharedMemory.__del__ at 0x757225135b80>\n",
      "cannot close exported pointers exist\n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 227, in close\n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 184, in __del__\n",
      "\n",
      "Exception ignored in: BufferError\n",
      "Traceback (most recent call last):\n",
      "    : BufferError      File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 184, in __del__\n",
      "self.close()<function SharedMemory.__del__ at 0x757225135b80>cannot close exported pointers exist: self._mmap.close()    \n",
      "\n",
      "cannot close exported pointers exist\n",
      "\n",
      "Exception ignored in:   File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 227, in close\n",
      "self.close()\n",
      "Traceback (most recent call last):\n",
      "BufferError    \n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 184, in __del__\n",
      "Exception ignored in: : <function SharedMemory.__del__ at 0x757225135b80>self._mmap.close()\n",
      "\n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 227, in close\n",
      "cannot close exported pointers exist    <function SharedMemory.__del__ at 0x757225135b80>BufferErrorTraceback (most recent call last):\n",
      "\n",
      "    self.close():   File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 184, in __del__\n",
      "\n",
      "self._mmap.close()cannot close exported pointers exist\n",
      "Traceback (most recent call last):\n",
      "    Exception ignored in:   File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 184, in __del__\n",
      "\n",
      "\n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 227, in close\n",
      "self.close()<function SharedMemory.__del__ at 0x757225135b80>    BufferError    \n",
      "self.close()\n",
      ": self._mmap.close()Exception ignored in: Traceback (most recent call last):\n",
      "\n",
      "cannot close exported pointers exist  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 227, in close\n",
      "\n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 184, in __del__\n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 227, in close\n",
      "<function SharedMemory.__del__ at 0x757225135b80>\n",
      "    BufferError        self._mmap.close()\n",
      ": self.close()self._mmap.close()\n",
      "cannot close exported pointers existTraceback (most recent call last):\n",
      "Exception ignored in: \n",
      "\n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 184, in __del__\n",
      "\n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 227, in close\n",
      "BufferError<function SharedMemory.__del__ at 0x757225135b80>BufferError        : \n",
      ": self._mmap.close()self.close()cannot close exported pointers existcannot close exported pointers exist\n",
      "Traceback (most recent call last):\n",
      "Exception ignored in: \n",
      "\n",
      "\n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 184, in __del__\n",
      "BufferError  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 227, in close\n",
      "<function SharedMemory.__del__ at 0x757225135b80>:         \n",
      "cannot close exported pointers existException ignored in: self.close()self._mmap.close()\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "<function SharedMemory.__del__ at 0x757225135b80>  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 184, in __del__\n",
      "BufferError  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 227, in close\n",
      "\n",
      "    :     Exception ignored in: Traceback (most recent call last):\n",
      "cannot close exported pointers existself.close()self._mmap.close()  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 184, in __del__\n",
      "<function SharedMemory.__del__ at 0x757225135b80>\n",
      "\n",
      "\n",
      "    \n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 227, in close\n",
      "self.close()BufferErrorTraceback (most recent call last):\n",
      "    Exception ignored in: \n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 184, in __del__\n",
      ": self._mmap.close()<function SharedMemory.__del__ at 0x757225135b80>  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 227, in close\n",
      "cannot close exported pointers exist    \n",
      "\n",
      "    \n",
      "self.close()BufferErrorTraceback (most recent call last):\n",
      "self._mmap.close()\n",
      "Exception ignored in: :   File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 184, in __del__\n",
      "\n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 227, in close\n",
      "cannot close exported pointers existBufferError<function SharedMemory.__del__ at 0x757225135b80>        : \n",
      "\n",
      "self._mmap.close()self.close()cannot close exported pointers existTraceback (most recent call last):\n",
      "\n",
      "\n",
      "Exception ignored in: \n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 184, in __del__\n",
      "BufferError  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 227, in close\n",
      "    : <function SharedMemory.__del__ at 0x757225135b80>self.close()cannot close exported pointers exist    \n",
      "\n",
      "\n",
      "self._mmap.close()Traceback (most recent call last):\n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 227, in close\n",
      "Exception ignored in:     \n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 184, in __del__\n",
      "self._mmap.close()<function SharedMemory.__del__ at 0x757225135b80>BufferError\n",
      "\n",
      "    BufferError: Traceback (most recent call last):\n",
      "self.close(): cannot close exported pointers exist\n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 184, in __del__\n",
      "cannot close exported pointers exist  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 227, in close\n",
      "\n",
      "\n",
      "        self.close()self._mmap.close()\n",
      "\n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 227, in close\n",
      "BufferErrorException ignored in: :     <function SharedMemory.__del__ at 0x757225135b80>cannot close exported pointers existself._mmap.close()\n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 184, in __del__\n",
      "BufferErrorException ignored in:     : <function SharedMemory.__del__ at 0x757225135b80>self.close()cannot close exported pointers exist\n",
      "\n",
      "\n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 227, in close\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 184, in __del__\n",
      "    self._mmap.close()    \n",
      "self.close()Exception ignored in: Exception ignored in: BufferError\n",
      ": <function SharedMemory.__del__ at 0x757225135b80>  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 227, in close\n",
      "<function SharedMemory.__del__ at 0x757225135b80>cannot close exported pointers exist\n",
      "    \n",
      "\n",
      "self._mmap.close()Traceback (most recent call last):\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 184, in __del__\n",
      "Exception ignored in: BufferError  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 184, in __del__\n",
      "    : <function SharedMemory.__del__ at 0x757225135b80>self.close()cannot close exported pointers exist    Exception ignored in: \n",
      "\n",
      "\n",
      "self.close()<function SharedMemory.__del__ at 0x757225135b80>  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 227, in close\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "      File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 184, in __del__\n",
      "Traceback (most recent call last):\n",
      "  0%|          | 0/508660 [00:00<?, ?it/s]  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 227, in close\n",
      "      File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 184, in __del__\n",
      "\n",
      "self.close()    <function SharedMemory.__del__ at 0x757225135b80>    \n",
      "BufferErrorException ignored in: self._mmap.close()\n",
      "self.close():   File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 227, in close\n",
      "<function SharedMemory.__del__ at 0x757225135b80>\n",
      "Traceback (most recent call last):\n",
      "\n",
      "cannot close exported pointers exist    BufferError\n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 227, in close\n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 184, in __del__\n",
      "\n",
      "self._mmap.close():         Traceback (most recent call last):\n",
      "\n",
      "cannot close exported pointers existself._mmap.close()self.close()  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 184, in __del__\n",
      "BufferError\n",
      "\n",
      "\n",
      "BufferError:       File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 227, in close\n",
      ": cannot close exported pointers existself.close()    \n",
      "cannot close exported pointers exist\n",
      "self._mmap.close()\n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 227, in close\n",
      "Exception ignored in: \n",
      "BufferError:     self._mmap.close()cannot close exported pointers existcannot close exported pointers exist\n",
      "\n",
      "BufferError: self.close()<function SharedMemory.__del__ at 0x757225135b80>\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 184, in __del__\n",
      "    \n",
      "  File \"/home/pablo/anaconda3/envs/LaboIII/lib/python3.9/multiprocessing/shared_memory.py\", line 227, in close\n",
      "    self._mmap.close()\n",
      "BufferError: cannot close exported pointers exist\n",
      " 63%|██████▎   | 321960/508660 [4:32:50<3:36:32, 14.37it/s] "
     ]
    }
   ],
   "source": [
    "\n",
    "# -------------------------------\n",
    "# 1. Función de limpieza\n",
    "# -------------------------------\n",
    "def es_serie_valida(s):\n",
    "    if not isinstance(s, list): return False\n",
    "    if len(s) < 3: return False\n",
    "    for v in s:\n",
    "        if not isinstance(v, (int, float)): return False\n",
    "        if isinstance(v, float) and np.isnan(v): return False\n",
    "    return True\n",
    "\n",
    "# Asumimos que ya tenés series_list\n",
    "series_list_limpia = [s for s in series_list if es_serie_valida(s)]\n",
    "print(f\"Series válidas: {len(series_list_limpia)} / {len(series_list)}\")\n",
    "\n",
    "# -------------------------------\n",
    "# 2. Muestreo\n",
    "# -------------------------------\n",
    "sample_size = min(1000, len(series_list_limpia))  # Ajustable\n",
    "np.random.seed(42)\n",
    "sample_idx = np.random.choice(len(series_list_limpia), sample_size, replace=False)\n",
    "sample_series = [series_list_limpia[i] for i in sample_idx]\n",
    "\n",
    "# -------------------------------\n",
    "# 3. Matriz de distancias entre muestras\n",
    "# -------------------------------\n",
    "def fastdtw_distance(s1, s2):\n",
    "    try:\n",
    "        dist, _ = fastdtw(s1, s2)\n",
    "        return dist\n",
    "    except:\n",
    "        return np.inf\n",
    "\n",
    "distance_matrix = np.zeros((sample_size, sample_size))\n",
    "print(\"Calculando matriz de distancias FastDTW...\")\n",
    "\n",
    "for i in tqdm(range(sample_size)):\n",
    "    for j in range(i + 1, sample_size):\n",
    "        d = fastdtw_distance(sample_series[i], sample_series[j])\n",
    "        distance_matrix[i, j] = distance_matrix[j, i] = d\n",
    "\n",
    "# -------------------------------\n",
    "# 4. MDS y clustering\n",
    "# -------------------------------\n",
    "print(\"Reduciendo dimensión con MDS...\")\n",
    "mds = MDS(n_components=10, dissimilarity='precomputed', random_state=42)\n",
    "embedding = mds.fit_transform(distance_matrix)\n",
    "\n",
    "clusterer = hdbscan.HDBSCAN(min_cluster_size=20)\n",
    "sample_labels = clusterer.fit_predict(embedding)\n",
    "\n",
    "# Si querés ver cuántos clusters reales se detectaron:\n",
    "n_clusters = len(set(sample_labels)) - (1 if -1 in sample_labels else 0)\n",
    "print(f\"Clusters detectados: {n_clusters}\")\n",
    "\n",
    "# -------------------------------\n",
    "# 5. SERIALIZAR sample_series y sample_labels a memoria compartida\n",
    "# -------------------------------\n",
    "sample_blob = pickle.dumps((sample_series, sample_labels))\n",
    "sample_shm = shared_memory.SharedMemory(create=True, size=len(sample_blob))\n",
    "sample_shm.buf[:len(sample_blob)] = sample_blob\n",
    "shm_name = sample_shm.name\n",
    "shm_size = len(sample_blob)\n",
    "\n",
    "# -------------------------------\n",
    "# 6. Función worker para asignar cluster\n",
    "# -------------------------------\n",
    "def init_worker(_shm_name, _shm_size):\n",
    "    global sample_data\n",
    "    shm = shared_memory.SharedMemory(name=_shm_name)\n",
    "    blob = shm.buf[:_shm_size]\n",
    "    sample_data = pickle.loads(blob)\n",
    "\n",
    "def asignar_cluster_worker(serie):\n",
    "    sample_series, sample_labels = sample_data\n",
    "    min_dist = float('inf')\n",
    "    min_label = -1\n",
    "    for s, label in zip(sample_series, sample_labels):\n",
    "        try:\n",
    "            d = fastdtw_distance(serie, s)\n",
    "        except:\n",
    "            d = float('inf')\n",
    "        if d < min_dist:\n",
    "            min_dist = d\n",
    "            min_label = label\n",
    "    return min_label\n",
    "\n",
    "# -------------------------------\n",
    "# 7. Paralelizar asignación\n",
    "# -------------------------------\n",
    "print(f\"Asignando clusters usando memoria compartida y {min(28, cpu_count())} procesos...\")\n",
    "with Pool(processes=28, initializer=init_worker, initargs=(shm_name, shm_size)) as pool:\n",
    "    cluster_labels = list(tqdm(pool.imap(asignar_cluster_worker, series_list_limpia), total=len(series_list_limpia)))\n",
    "\n",
    "# -------------------------------\n",
    "# 8. Guardar resultados\n",
    "# -------------------------------\n",
    "df_resultado = pd.DataFrame({\n",
    "    'serie_clase': series_list_limpia,\n",
    "    'cluster': cluster_labels\n",
    "})\n",
    "df_resultado.to_parquet(\"series_clusterizadas.parquet\", index=False)\n",
    "\n",
    "print(\"✅ Clustering completo y resultado guardado.\")\n",
    "\n",
    "# Liberar memoria compartida\n",
    "sample_shm.close()\n",
    "sample_shm.unlink()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "LaboIII",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.23"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
